In [1]:
import numpy as np
import numpy.linalg as la

This is our micro-internet.
<img src="images/Link_graph.png"></img>

Imagine we have 100 Procrastinating Pats on our micro-internet, each viewing a single website at a time. Each minute the Pats follow a link on their website to another site on the micro-internet. After a while, the websites that are most linked to will have more Pats visiting them, and in the long run, each minute for every Pat that leaves a website, another will enter keeping the total numbers of Pats on each website constant. The PageRank is simply the ranking of websites by how many Pats they have on them at the end of this process.

In [14]:
L = np.array([[0, 1/3, 1/3, 1/3],[1/2 ,0, 0, 1/2],[0, 0, 0, 1],[0, 1/2 , 1/2, 0]]).T
L

array([[0.        , 0.5       , 0.        , 0.        ],
       [0.33333333, 0.        , 0.        , 0.5       ],
       [0.33333333, 0.        , 0.        , 0.5       ],
       [0.33333333, 0.5       , 1.        , 0.        ]])

In [15]:
eVals, eVecs = la.eig(L) # Gets the eigenvalues and vectors

In [16]:
eVals #we only care about the principal eigenvector (the one with the largest eigenvalue, which will be 1 in this case)

array([ 1.00000000e+00, -9.17517095e-02, -9.08248290e-01,  5.88174157e-17])

In [17]:
order = np.absolute(eVals).argsort()[::-1] # Orders them by their eigenvalues
eVals = eVals[order]
eVecs = eVecs[:,order]

In [18]:
eVals

array([ 1.00000000e+00, -9.08248290e-01, -9.17517095e-02,  5.88174157e-17])

In [19]:
eVecs

array([[-2.22988244e-01,  2.62323812e-01, -8.25340062e-01,
        -8.01783726e-01],
       [-4.45976488e-01, -4.76510307e-01,  1.51452723e-01,
        -1.04906215e-16],
       [-4.45976488e-01, -4.76510307e-01,  1.51452723e-01,
         2.67261242e-01],
       [-7.43294146e-01,  6.90696802e-01,  5.22434615e-01,
         5.34522484e-01]])

In [20]:
r = eVecs[:, 0] # Sets r to be the principal eigenvector
100 * np.real(r / np.sum(r)) # Make this eigenvector sum to one, then multiply by 100 Procrastinating Pats

array([12., 24., 24., 40.])

We can see from this list, the number of Procrastinating Pats that we expect to find on each website after long times. Putting them in order of popularity (based on this metric), the PageRank of this micro-internet is:

    D => 40 pats

    C & B => 24 each

    A => 12

In principle, we could use a linear algebra library, as above, to calculate the eigenvalues and vectors. And this would work for a small system. But this gets unmanagable for large systems. And since we only care about the principal eigenvector (the one with the largest eigenvalue, which will be 1 in this case), we can use the power iteration method which will scale better, and is faster for large systems.

In [22]:
d = 0.5
n  = 4
M = d * L + (1-d)/n * np.ones([n, n])

In [23]:
M

array([[0.125     , 0.375     , 0.125     , 0.125     ],
       [0.29166667, 0.125     , 0.125     , 0.375     ],
       [0.29166667, 0.125     , 0.125     , 0.375     ],
       [0.29166667, 0.375     , 0.625     , 0.125     ]])

In [24]:
r = 100 * np.ones(n) / n # Sets up this vector (6 entries of 1/6 × 100 each)
lastR = r
r = M @ r
i = 0
while la.norm(lastR - r) > 0.01 :
    lastR = r
    r = M @ r
    i += 1
print(str(i) + " iterations to convergence.")

9 iterations to convergence.


In [26]:
r

array([18.49264323, 23.97352452, 23.97352452, 33.56030772])

In [27]:
np.sum(r)

99.99999999999999